// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// 102 # 1 "com/donhatchsw/util/NewtonSolver.prejava"
// 103 # 1 "<built-in>"
// 104 # 1 "<command-line>"
// 105 # 1 "com/donhatchsw/util/NewtonSolver.prejava"
/* vim: set filetype=java: */
package com.donhatchsw.util;
// 108 # 1 "com/donhatchsw/util/macros.h" 1
//
// macros.h
//
// 112 # 14 "com/donhatchsw/util/macros.h"
// NOTE: this causes a,b to be evaluated twice on failure, so is not ideal. might be better to do a block... ?
// 114 # 30 "com/donhatchsw/util/macros.h"
// Note: the additional "(a)==(b)||" is to make it work correctly for infinities...
// and causes the args to be evaluated twice.
// 117 # 67 "com/donhatchsw/util/macros.h"
// XXX ... what a mess
// 119 # 4 "com/donhatchsw/util/NewtonSolver.prejava" 2

public class NewtonSolver
{
    public abstract static class Fun
    {
        int dim;
        private double xplusdx[/*dim*/]; // scratch for J
        private double f_xplusdx[/*dim*/]; // scratch for J
        public Fun(int dim)
        {
            this.dim = dim;
            this.xplusdx = new double[dim];
            this.f_xplusdx = new double[dim];
        }

        /**
        * Derived class must implement f
        */
        public abstract void f(double x[], double answer[]);
        /**
        * Derived class may implement jacobian if they wish.
        * if they don't, they will get this default
        * implementation which estimates the jacobian
        * using finite differences.
        * The fx that is passed to this function during a newton solve is always f(x),
        * in case the computation of J(x) finds it useful.
        */
        public void J(double x[], double fx[], double answer[/*dim*/][/*dim*/])
        {
            double dx = tol();
            double invdx = 1./dx;
            VecMath.copyvec(dim, xplusdx, x); // into scratch
            for (int iCol = 0; (iCol) < (dim); ++iCol)
            {
                xplusdx[iCol] += dx; // temporarily change just this entry
                f(xplusdx, f_xplusdx); // f_xplusdx = f(xplusdx);
                for (int iRow = 0; (iRow) < (dim); ++iRow)
                    answer[iRow][iCol] = (f_xplusdx[iRow]-fx[iRow]) * invdx;
                xplusdx[iCol] = x[iCol]; // restore this entry
            }
            //PRINTMAT(answer);
        }
        // the default J() uses this for the finite difference.
        // derived classes may implement this
        // to make it use a different finite difference.
        // Best practice is probably to normalize the problem size so that the maximum
        // value occurring in the problem is around 1.
        // XXX change to 1e-6?  should list reasons for wanting different values.
        // XXX CatenaryRotated currently (not numerically stabilized yet) doesn't like 1e-4 but likes 1e-6.
        public double tol()
        {
            return 1e-4;
        }
    } // abstract static class Fun

    /**
    * x should be loaded with the initial guess;
    * it will be refined.
    */
    public static void solve(double x[],
                             double y[], // const
                             Fun fun,
                             int minIterations, // seem to need this, or it thinks it stopped improving after 1 iteration in some sticky situations.  I think actually the termination condition should be that it didn't improve in some number of iterations? hmm. actually should make it smart and adaptive I think.
                             int maxIterations,
                             boolean adaptiveFlag)
    {
        boolean debug = false;
        if (debug) System.out.println("    in solve(x="+VecMath.toString(x)+", y="+VecMath.toString(y)+", maxIterations="+maxIterations+", adaptiveFlag="+adaptiveFlag);
        if (debug) {System.out.print("        "); System.out.println("maxIterations" + " = " + (maxIterations));};
        int dim = fun.dim;
        double prevPrevErrorLengthSqrd = Double.POSITIVE_INFINITY;
        double prevErrorLengthSqrd = Double.POSITIVE_INFINITY;
        double fx[] = new double[dim]; // scratch
        double error[] = new double[dim]; // scratch
        double Jx[][] = new double[dim][dim]; // scratch
        double fullCorrection[] = new double[dim]; // scratch

        for (int iIter = 0; (iIter) < (maxIterations); ++iIter)
        {
            if (debug) {System.out.print("        "); System.out.println("iIter" + " = " + (iIter));};
            if (debug) System.out.println("        " + "x" + " = " + VecMath.toString(x));
            if (debug) System.out.println("        " + "y" + " = " + VecMath.toString(y));

            if (iIter==0 || !adaptiveFlag) // if haven't already calculated it
                fun.f(x, fx); // fx = f(x);

            if (debug) System.out.println("        " + "fx" + " = " + VecMath.toString(fx));

            VecMath.vmv(error, fx, y);
            double errorLengthSqrd = VecMath.normsqrd(error);
            if (debug) {System.out.print("        "); System.out.println("errorLengthSqrd" + " = " + (errorLengthSqrd));};
            if (debug) {System.out.print("        "); System.out.println("Math.sqrt(errorLengthSqrd)" + " = " + (Math.sqrt(errorLengthSqrd)));};
            if (Double.isNaN(errorLengthSqrd) || Double.isInfinite(errorLengthSqrd))
            {
                if (debug) System.out.println("    out solve (NaN or infinite)");
                return;
            }
            if (iIter >= minIterations
             && !(errorLengthSqrd < prevErrorLengthSqrd))
             // XXX something about prevPrev? think about it
            {
                if (debug) System.out.println("    out solve (stopped improving after "+iIter+" iterations");
                return;
            }
            prevPrevErrorLengthSqrd = prevErrorLengthSqrd;
            prevErrorLengthSqrd = errorLengthSqrd;

            // One newton iteration:
            // If we want to find x such that f(x) = y,
            // start with xGuess
            // and evaluate J = df/dx at xGuess.
            // Then, approximately,
            //       J(xGuess) * (x-xGuess) = (y - f(xGuess)
            //                    x-xGuess = J^-1 * (y - f(xGuess))
            //                    x = xGuess + J^-1 * (y - f(xGuess))


            fun.J(x, fx, Jx); // Jx = J(x, fx)

            // Sanity check J, so we don't get assert fails down in invmxv
            for (int i = 0; i < Jx.length; ++i)
            for (int j = 0; j < Jx[i].length; ++j)
            {
                do { if (!(!Double.isNaN(Jx[i][j]))) throw new Error("CHECK failed at "+"com/donhatchsw/util/NewtonSolver.prejava"+"("+127 +"): " + "!Double.isNaN(Jx[i][j])" + ""); } while (false);
            }

            // TODO: get rid of memory allocations!!
            // x += Jx^-1 * (y - fx)
            VecMath.invmxv(fullCorrection,
                           Jx,
                           VecMath.vmv(y, fx)); // XXX wait a minute, isn't that -error?
            if (!adaptiveFlag)
            {
                // Naive implementation
                VecMath.vpv(x, x, fullCorrection);
            }
            else
            {
                // Adaptive. If it's too wild, half the step size, til it's sane.
                double prevErrorLength = Math.sqrt(prevErrorLengthSqrd);
                double maxStepScale = 1.; // can set this to something less to force it to be gentle and slow for debugging
                for (double stepScale = maxStepScale; ; stepScale *= .5)
                {
                    do { if (!(stepScale > 0.)) throw new Error("CHECK failed at "+"com/donhatchsw/util/NewtonSolver.prejava"+"("+147 +"): " + "stepScale > 0." + ""); } while (false);
                    double xNewMaybe[] = VecMath.vpsxv(x,
                                                       stepScale,
                                                       fullCorrection);
                    double fxNewMaybe[] = new double[dim];
                    fun.f(xNewMaybe, fxNewMaybe); // fxNewMaybe = f(xNewMaybe)
                    double ySortOf[] = VecMath.lerp(fx, y, stepScale);
                    if (debug) System.out.println("        " + "xNewMaybe" + " = " + VecMath.toString(xNewMaybe));
                    if (debug) System.out.println("        " + "fxNewMaybe" + " = " + VecMath.toString(fxNewMaybe));
                    VecMath.vmv(error, fxNewMaybe, ySortOf);
                    double newErrorLengthSqrd = VecMath.normsqrd(error);
                    double newErrorLength = Math.sqrt(newErrorLengthSqrd);
                    if (debug) {System.out.print("        "); System.out.println("newErrorLength" + " = " + (newErrorLength));};
                    if (newErrorLength <= .5 * prevErrorLength * stepScale)
                    {
                        VecMath.copyvec(x, xNewMaybe);
                        VecMath.copyvec(fx, fxNewMaybe);
                        // TODO: the next call to f will be redundant with the one we just did; should fix that
                        break;
                    }
                    // Too wild; pull back to half as far
                    if (debug) System.out.println("        too wild! stepScale "+stepScale+" -> "+(stepScale*.5)+"");
                }
            }
        }
        if (debug) System.out.println("    out solve (maxIterations="+maxIterations+" reached)");
    } // solve

    // Little test program
    public static void main(String args[])
    {
        System.out.println("    in NewtonSolver.main");
        {
            // Find x such that x^2 == 100, with starting guess of 9
            Fun fun = new Fun(1) {
                @Override public void f(double x[], double fx[])
                {
                    fx[0] = x[0]*x[0];
                }
            };
            double x[] = {9}; // initial guess
            double y[] = {100};

            solve(x, y, fun, 10, 1000, false);
        }
        {
            // find x0,x1 such that {x0*x0,x0*x1} == {100,200}
            // (answer is 10,20)
            Fun fun = new Fun(2) {
                @Override public void f(double x[], double fx[])
                {
                  fx[0] = x[0]*x[0];
                  fx[1] = x[0]*x[1];
                }
            };
            double x[] = {5,25}; // initial guess
            double y[] = {100,200};

            solve(x, y, fun, 10, 1000, false);
        }
        // XXX TODO: exercise adaptiveFlag
        System.out.println("    out NewtonSolver.main");
    } // main
} // class NewtonSolver
