// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// 102 # 1 "com/donhatchsw/compat/DoubleArrayList.prejava"
// 103 # 1 "<built-in>"
// 104 # 1 "<command-line>"
// 105 # 1 "com/donhatchsw/compat/DoubleArrayList.prejava"
/* vim: set filetype=java: */
package com.donhatchsw.compat;
// 108 # 1 "com/donhatchsw/compat/macros.h" 1
//
// macros.h
//
// 112 # 14 "com/donhatchsw/compat/macros.h"
// NOTE: this causes a,b to be evaluated twice on failure, so is not ideal. might be better to do a block... ?
// 114 # 30 "com/donhatchsw/compat/macros.h"
// Note: the additional "(a)==(b)||" is to make it work correctly for infinities...
// and causes the args to be evaluated twice.
// 117 # 67 "com/donhatchsw/compat/macros.h"
// XXX ... what a mess
// 119 # 4 "com/donhatchsw/compat/DoubleArrayList.prejava" 2
/**
* ArrayList<double>.
* Not optimized (but it could be).
*/
public class DoubleArrayList
{
    private ArrayList arrayList;

    public DoubleArrayList(int initialCapacity)
    {
        arrayList = new ArrayList(initialCapacity);
    }
    public DoubleArrayList()
    {
        arrayList = new ArrayList();
    }
    public DoubleArrayList(ArrayList from) // this is Collection in the real ArrayList
    {
        arrayList = new ArrayList(from);
    }
    public void trimToSize()
    {
        arrayList.trimToSize();
    }
    public void ensureCapacity(int minCapacity)
    {
        arrayList.ensureCapacity(minCapacity);
    }
    public int size()
    {
        return arrayList.size();
    }
    public boolean isEmpty()
    {
        return arrayList.isEmpty();
    }
    public boolean contains(double element)
    {
        return arrayList.contains(Double.valueOf(element));
    }
    public int indexOf(double element)
    {
        return arrayList.indexOf(Double.valueOf(element));
    }
    public int lastIndexOf(double element)
    {
        return arrayList.lastIndexOf(Double.valueOf(element));
    }
    public java.lang.Object clone()
    {
        DoubleArrayList cloned = new DoubleArrayList();
        cloned.arrayList = (ArrayList)this.arrayList.clone();
        return cloned;
    }
    public double[] toArray()
    {
        return toArray(new double[arrayList.size()]);
    }
    public double[] toArray(double[] to)
    {
        if (to.length < arrayList.size())
            return toArray();
        for (int i = 0; i < arrayList.size(); ++i)
            to[i] = ((Double)arrayList.get(i)).doubleValue();
        return to;
    }
    public double get(int index)
    {
        return ((Double)arrayList.get(index)).doubleValue();
    }
    public double set(int index, double element)
    {
        return ((Double)arrayList.set(index, Double.valueOf(element))).doubleValue();
    }
    public boolean add(double element)
    {
        return arrayList.add(Double.valueOf(element));
    }
    public void add(int index, double element)
    {
        arrayList.add(index, Double.valueOf(element));
    }
    /** the version of remove() that takes an index */
    public double removeIndex(int index)
    {
        return ((Double)arrayList.remove(index)).doubleValue();
    }
    /** the version of remove() that takes an element */
    /** XXX javap says boolean, some doc says it returns an Object, some other doc doesn't mention it at all... fuck it, I'm returning void. */
    public void removeElement(double element)
    {
        arrayList.remove(Double.valueOf(element));
    }
    public void clear()
    {
        arrayList.clear();
    }
    public boolean addAll(DoubleArrayList from) // this is Collection in the real ArrayList
    {
        return arrayList.addAll(from.arrayList);
    }
    public boolean addAll(int index, DoubleArrayList from) // this is Collection in the real ArrayList
    {
        return arrayList.addAll(index, from.arrayList);
    }
    protected void removeRange(int fromIndex, int toIndex)
    {
        arrayList.removeRange(fromIndex, toIndex);
    }

    /** test program */
    public static void main(String args[])
    {
        DoubleArrayList a = new DoubleArrayList();
        do { if (!((a.size())==(0))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/DoubleArrayList.prejava"+"("+118 +"): (" + "a.size()" + ")" + "==" + "(" + "0" + ") ("+(a.size())+" vs. "+(0)+")"); } while (false);
        a.add(100.);
        do { if (!((a.size())==(1))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/DoubleArrayList.prejava"+"("+120 +"): (" + "a.size()" + ")" + "==" + "(" + "1" + ") ("+(a.size())+" vs. "+(1)+")"); } while (false);
        a.add(200.);
        do { if (!((a.size())==(2))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/DoubleArrayList.prejava"+"("+122 +"): (" + "a.size()" + ")" + "==" + "(" + "2" + ") ("+(a.size())+" vs. "+(2)+")"); } while (false);
        a.add(-1.);
        do { if (!((a.size())==(3))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/DoubleArrayList.prejava"+"("+124 +"): (" + "a.size()" + ")" + "==" + "(" + "3" + ") ("+(a.size())+" vs. "+(3)+")"); } while (false);
        a.removeIndex(a.size()-1);
        do { if (!((a.size())==(2))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/DoubleArrayList.prejava"+"("+126 +"): (" + "a.size()" + ")" + "==" + "(" + "2" + ") ("+(a.size())+" vs. "+(2)+")"); } while (false);
        a.add(300.);
        do { if (!((a.size())==(3))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/DoubleArrayList.prejava"+"("+128 +"): (" + "a.size()" + ")" + "==" + "(" + "3" + ") ("+(a.size())+" vs. "+(3)+")"); } while (false);
        a.clear();
        do { if (!((a.size())==(0))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/DoubleArrayList.prejava"+"("+130 +"): (" + "a.size()" + ")" + "==" + "(" + "0" + ") ("+(a.size())+" vs. "+(0)+")"); } while (false);
        System.out.println("All good!");
    }
} // class ArrayList
