// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// 102 # 1 "com/donhatchsw/compat/IntArrayList.prejava"
// 103 # 1 "<built-in>"
// 104 # 1 "<command-line>"
// 105 # 1 "com/donhatchsw/compat/IntArrayList.prejava"
/* vim: set filetype=java: */
package com.donhatchsw.compat;
// 108 # 1 "com/donhatchsw/compat/macros.h" 1
//
// macros.h
//
// 112 # 14 "com/donhatchsw/compat/macros.h"
// NOTE: this causes a,b to be evaluated twice on failure, so is not ideal. might be better to do a block... ?
// 114 # 30 "com/donhatchsw/compat/macros.h"
// Note: the additional "(a)==(b)||" is to make it work correctly for infinities...
// and causes the args to be evaluated twice.
// 117 # 67 "com/donhatchsw/compat/macros.h"
// XXX ... what a mess
// 119 # 4 "com/donhatchsw/compat/IntArrayList.prejava" 2
/**
* ArrayList<int>.
* Not optimized (but it could be).
*/
public class IntArrayList
{
    private ArrayList arrayList;

    public IntArrayList(int initialCapacity)
    {
        arrayList = new ArrayList(initialCapacity);
    }
    public IntArrayList()
    {
        arrayList = new ArrayList();
    }
    public IntArrayList(ArrayList from) // this is Collection in the real ArrayList
    {
        arrayList = new ArrayList(from);
    }
    public void trimToSize()
    {
        arrayList.trimToSize();
    }
    public void ensureCapacity(int minCapacity)
    {
        arrayList.ensureCapacity(minCapacity);
    }
    public int size()
    {
        return arrayList.size();
    }
    public boolean isEmpty()
    {
        return arrayList.isEmpty();
    }
    public boolean contains(int element)
    {
        return arrayList.contains(Integer.valueOf(element));
    }
    public int indexOf(int element)
    {
        return arrayList.indexOf(Integer.valueOf(element));
    }
    public int lastIndexOf(int element)
    {
        return arrayList.lastIndexOf(Integer.valueOf(element));
    }
    public java.lang.Object clone()
    {
        IntArrayList cloned = new IntArrayList();
        cloned.arrayList = (ArrayList)this.arrayList.clone();
        return cloned;
    }
    public int[] toArray()
    {
        return toArray(new int[arrayList.size()]);
    }
    public int[] toArray(int[] to)
    {
        if (to.length < arrayList.size())
            return toArray();
        for (int i = 0; i < arrayList.size(); ++i)
            to[i] = ((Integer)arrayList.get(i)).intValue();
        return to;
    }
    public int get(int index)
    {
        return ((Integer)arrayList.get(index)).intValue();
    }
    public int set(int index, int element)
    {
        return ((Integer)arrayList.set(index, Integer.valueOf(element))).intValue();
    }
    public boolean add(int element)
    {
        return arrayList.add(Integer.valueOf(element));
    }
    public void add(int index, int element)
    {
        arrayList.add(index, Integer.valueOf(element));
    }
    /** the version of remove() that takes an index */
    public int removeIndex(int index)
    {
        return ((Integer)arrayList.remove(index)).intValue();
    }
    /** the version of remove() that takes an element */
    /** XXX javap says boolean, some doc says it returns an Object, some other doc doesn't mention it at all... fuck it, I'm returning void. */
    public void removeElement(int element)
    {
        arrayList.remove(Integer.valueOf(element));
    }
    public void clear()
    {
        arrayList.clear();
    }
    public boolean addAll(IntArrayList from) // this is Collection in the real ArrayList
    {
        return arrayList.addAll(from.arrayList);
    }
    public boolean addAll(int index, IntArrayList from) // this is Collection in the real ArrayList
    {
        return arrayList.addAll(index, from.arrayList);
    }
    protected void removeRange(int fromIndex, int toIndex)
    {
        arrayList.removeRange(fromIndex, toIndex);
    }

    /** test program */
    public static void main(String args[])
    {
        IntArrayList a = new IntArrayList();
        do { if (!((a.size())==(0))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/IntArrayList.prejava"+"("+118 +"): (" + "a.size()" + ")" + "==" + "(" + "0" + ") ("+(a.size())+" vs. "+(0)+")"); } while (false);
        a.add(100);
        do { if (!((a.size())==(1))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/IntArrayList.prejava"+"("+120 +"): (" + "a.size()" + ")" + "==" + "(" + "1" + ") ("+(a.size())+" vs. "+(1)+")"); } while (false);
        a.add(200);
        do { if (!((a.size())==(2))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/IntArrayList.prejava"+"("+122 +"): (" + "a.size()" + ")" + "==" + "(" + "2" + ") ("+(a.size())+" vs. "+(2)+")"); } while (false);
        a.add(-1);
        do { if (!((a.size())==(3))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/IntArrayList.prejava"+"("+124 +"): (" + "a.size()" + ")" + "==" + "(" + "3" + ") ("+(a.size())+" vs. "+(3)+")"); } while (false);
        a.removeIndex(a.size()-1);
        do { if (!((a.size())==(2))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/IntArrayList.prejava"+"("+126 +"): (" + "a.size()" + ")" + "==" + "(" + "2" + ") ("+(a.size())+" vs. "+(2)+")"); } while (false);
        a.add(300);
        do { if (!((a.size())==(3))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/IntArrayList.prejava"+"("+128 +"): (" + "a.size()" + ")" + "==" + "(" + "3" + ") ("+(a.size())+" vs. "+(3)+")"); } while (false);
        a.clear();
        do { if (!((a.size())==(0))) throw new Error("CHECK failed at "+"com/donhatchsw/compat/IntArrayList.prejava"+"("+130 +"): (" + "a.size()" + ")" + "==" + "(" + "0" + ") ("+(a.size())+" vs. "+(0)+")"); } while (false);
        System.out.println("All good!");
    }
} // class ArrayList
