// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// !!! THIS FILE WAS AUTOMATICALLY GENERATED BY javacpp; DO NOT EDIT !!!
// 102 # 1 "com/donhatchsw/awt/LayoutExample.prejava"
// 103 # 1 "<built-in>"
// 104 # 1 "<command-line>"
// 105 # 1 "com/donhatchsw/awt/LayoutExample.prejava"
/* vim: set filetype=java: */
package com.donhatchsw.awt;
import java.awt.*;
public class LayoutExample
{

    /**
        Test program, creates the following panel
        in a concise single statement:
        <pre>
        +----------------------------+
        |I:                          |
        | -------------------------- |
        |  |A:                       |
        |  | ---------------------   |
        |  |   |1: | aa | b | c      |
        |  |   |-----------------    |
        |  |   |2: | d | eee | f     |
        |  |-----------------------  |
        |  |B:                       |
        |  | ---------------------   |
        |  |   |1: | aa              |
        |  |   |-----------------    |
        |  |   |2: | a | b           |
        |----------------------------|
        |II:                         |
        | -------------------------- |
        |  |M:                       |
        |  |-----------------------  |
        |  |  |m00|m01               |
        |  |  |---+---------------   |
        |  |  |m10|m11               |
        +----------------------------+
        </pre>
    */

    @SuppressWarnings("serial")
    private static class LabeledCol
        extends Col
    {
        private static final GridBagConstraints stretchxy = new GridBagConstraints(){{fill=BOTH; weightx=weighty=1.;}};
        private Col theRealCol;
        public LabeledCol(final String topLabelText,
                          final String sideLabelText)
        {
            super.add(new Label(topLabelText)); // super so I don't call my own!
            super.add(new Row() {{ // super so I don't call my own!
                this.add(new Label(sideLabelText));
                this.add(theRealCol = new Col(), stretchxy);
            }}, stretchxy);
        }
        @Override public Component add(Component comp)
        {
            theRealCol.add(comp);
            return comp;
        }
        @Override public void add(Component comp, Object constraints)
        {
            theRealCol.add(comp, constraints);
        }
    }

    private static void randomlyColorize(Component c)
    {
        c.setBackground(new java.awt.Color((float)Math.random(),
                                           (float)Math.random(),
                                           (float)Math.random()));
        c.setForeground(new java.awt.Color((float)Math.random(),
                                           (float)Math.random(),
                                           (float)Math.random()));
        if (c instanceof Container)
        {
            Container C = (Container)c;
            int n = C.getComponentCount();
            for (int i = 0; i < n; ++i)
                randomlyColorize(C.getComponent(i));
        }
    } // randomlyColorize

    @SuppressWarnings("serial")
    public static void main(String args[])
    {
        {
            final GridBagConstraints stretchxy = new GridBagConstraints(){{fill=BOTH; weightx=weighty=1.;}};
            new Frame("TableLayout, RowLayout, ColLayout Test") {{
                setLayout(new ColLayout());
                add(new Col() {{
                    add(new LabeledCol("I:"," ") {{
                        add(new LabeledCol("A:"," ") {{
                            add(new Row() {{
                                add(new Label("1:"));
                                add(new Button("aa") {{
                                    addActionListener(new java.awt.event.ActionListener() {
                                        @Override public void actionPerformed(java.awt.event.ActionEvent e)
                                        {
                                            System.out.println("aa button pressed!");
                                        }
                                    });
                                }});
                                add(new Button("b"));
                                add(new Button("c"));
                            }});
                            add(new Row() {{
                                add(new Label("2:"));
                                add(new Button("d"));
                                add(new Button("eee"));
                                add(new Button("f"));
                            }});
                        }});
                        add(new LabeledCol("B:"," ") {{
                            add(new Row() {{
                                add(new Label("1:"));
                                add(new Button("aa"));
                            }});
                            add(new Row() {{
                                add(new Label("2:"));
                                add(new Button("a"));
                                add(new Button("b"));
                            }});
                        }});
                    }});
                    add(new LabeledCol("II:"," ") {{
                        add(new LabeledCol("M:"," ") {{
                            add(new TablePanel() {{
                                add(new Button("m00"), stretchxy);
                                add(new Button("m01"), stretchxy);
                                advanceRow();
                                add(new Button("0"), stretchxy);
                                add(new Button("m11"), stretchxy);
                            }});
                        }});
                    }});
                }});
                if (false)
                    randomlyColorize(this);

                pack();

                addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override public void windowClosing(java.awt.event.WindowEvent we)
                    {
                        dispose();
                        System.exit(0); // makes it exit quicker on my machine
                    }
                });

                setVisible(true); // available in java 1.5, replaces deprecated show()
            }};
        }

        // Stealing from
        // http://java.sun.com/docs/books/tutorial/uiswing/layout/spring.html
        // to make sure we can do it easily...
        // Oh, I guess an odd amount of inter-item spacing is awkward.
        // WhatEVER.
        if (false)
        {
            final GridBagConstraints constraints = new GridBagConstraints(){{fill=BOTH; weightx=1.; weighty=1.; insets = new Insets(3,3,0,0);}};
            new javax.swing.JFrame("Compact grid using TableLayout") {{
                setContentPane(new TablePanel() {{
                    int rows = 10;
                    int cols = 10;
                    for (int r = 0; r < rows; r++) {
                        for (int c = 0; c < cols; c++) {
                            int anInt = (int) Math.pow(r, c);
                            add(new javax.swing.JTextField(Integer.toString(anInt)),constraints);
                        }
                        add(new Canvas(){{setSize(3,3);}}); // fudge right pad
                        advanceRow();
                    }
                }});
                add(new Canvas(){{setSize(3,3);}}); // fudge bottom pad
                if (false)
                    randomlyColorize(this);

                pack();

                addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override public void windowClosing(java.awt.event.WindowEvent we)
                    {
                        dispose();
                        System.exit(0); // makes it exit quicker on my machine
                    }
                });

                setVisible(true); // available in java 1.5, replaces deprecated show()
            }};
        }
    } // main


} // class LayoutExample
